export const SET_GAME = 'SET_GAME'
export const SET_NAME = 'SET_NAME'
export const SET_LIFE = 'SET_LIFE'
export const SET_ENERGY = 'SET_ENERGY'
export const SET_ENTERTAINMENT = 'SET_ENTERTAINMENT'
export const DECREASE = 'DECREASE'
